### ISSUE TITLE
Milestone 1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI522_sreya_fwu#34]
Very well done!
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [x] Please list the references using the proper format. 

**Reasoning**
- [x] In the intro of your report, please give a sentence or two (max) explaining the relevance or importance of your question. 
- [x] Its a good idea to graph your cross-validation accuracy vs tree depth. 
- [x] You presented a figure of the decision tree. What does it mean? 

**Visualization**
- [x] More descriptive Figure and table captions. Captions should stand alone. Meaning, the reader should understand the figure by examining the graph and caption alone, and not refer back to the text. For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)"
- [x] I am having a hard time understanding Table 5. What do the numbers mean? Can you show a few more features just so that we can compare how important these 5 are compared to the other features? 

**Quality -- Readability and Documentation**
Good job!

**Quality -- Robustness and Maintainability**
- [ ] Should have a unit test in each script (because we did not clearly mention this in the instructions, we did not deduct points for not having a unit test)

**Grammar and Spelling**
_README.md:_
- [x] Misspelled  "depth" and "visualization" in the main README.md. 

> ...following code on command line to...

- [x] A  definite or indefinite article should precede the word "command." 

_Report:_
- [x] Misspelled important and achieved.

**Comment by sreyaguha** [comment]
Rectified the  checked issues.

**Comment by sreyaguha** [comment]
README updated with correct spellings

**Comment by fwu03** [comment]
add decision tree description, and explanation about table 5

**Comment by aimirza** [comment]
- Figure 4 image does not display in the report (md format). 
- You found the two most important features and you gave each one an "importance" number. So how important are these features? Also, discuss what this implies. Discuss the results a little, don't just state the results.
